(define (problem move_small_objects_to_a)
  (:domain shakey)
  (:objects rooma roomb roomc switcha switchb switchc boxa wideab widebc narrowbc left right blockx blocky blockz)
  (:init (room rooma)
          (room roomb)
	  (room roomc)
	  (door wideab)
	  (door widebc)
	  (door narrowbc)
	  (small-object blockx)
	  (small-object blocky)
	  (small-object blockz)
	  (lightswitch switcha)
	  (lightswitch switchb)
	  (lightswitch switchc)
	  (box boxa)
          (gripper left)
          (gripper right)
          (at-shakey rooma)
          (free left)
          (free right)
	  (wide wideab)
	  (wide widebc)
	  (door-between wideab rooma roomb)
	  (door-between wideab roomb rooma)
	  (door-between widebc roomb roomc)
	  (door-between widebc roomc roomb)
	  (door-between narrowbc roomb roomc)
	  (door-between narrowbc roomc roomb)
	  (at boxa roomc)
	  (at switcha rooma)
          (at switchb roomb)
	  (at switchc roomc)
	  (at blockx roomb)
	  (at blocky roomc)
	  (at blockz roomc)
	  )
   (:goal (and (lightswitch-on switcha) (not (lightswitch-on switchb)) (not (lightswitch-on switchc))
	       (at blockx rooma) (at blocky rooma) (at blockz rooma) (at-shakey rooma)
          )
   )
)