(define (problem turn_on_every_light)
  (:domain shakey)
  (:objects rooma roomb roomc switcha switchb switchc boxa wideab widebc narrowbc left right)
  (:init (room rooma)
          (room roomb)
	  (room roomc)
	  (door wideab)
	  (door widebc)
	  (door narrowbc)
	  (lightswitch switcha)
	  (lightswitch switchb)
	  (lightswitch switchc)
	  (box boxa)
          (gripper left)
          (gripper right)
          (at-shakey rooma)
          (free left)
          (free right)
	  (wide wideab)
	  (wide widebc)
	  (door-between wideab rooma roomb)
	  (door-between wideab roomb rooma)
	  (door-between widebc roomb roomc)
	  (door-between widebc roomc roomb)
	  (door-between narrowbc roomb roomc)
	  (door-between narrowbc roomc roomb)
	  (at boxa roomc)
	  (at switcha rooma)
          (at switchb roomb)
	  (at switchc roomc)
	  )
   (:goal (and (lightswitch-on switcha) (lightswitch-on switchb) (lightswitch-on switchc))
)
   )